Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
CAT_COLORS = %w(black white gray orange)

class Cat < ApplicationRecord

  include ActionView::Helpers::DateHelper

  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: {in: CAT_COLORS,
    message: "We do not rent those kinds of cats"}
  validates :sex, inclusion: {in: %w(M F),
    message: "We do not rent those kinds of cats"}


  def self.age
    time_ago_in_words(birth_date)
  end



end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    # debugger
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/views/cats/edit.html.erb
<h1>Tell us about your Cat</h1>
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <label for="name">Name: </label>

  <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">
  <br>
  <br>

  <label for="sex">Sex: </label>
    <label for="female">F</label>
    <input id="sex female" type="radio" name="cat[sex]" value="<%= @cat.sex %>" checked />
    <label for="male">M</label>
    <input id="sex male" type="radio" name="cat[sex]" value="<%= @cat.sex %>" />

  <label for="color">Color: </label>
  <select id="color" name="cat[color]">
    <option selected ><%= @cat.color %></option>
    <% CAT_COLORS.each do |c| %>
      <% next if c == @cat.color %>
      <option ><%= c %></option>
    <% end %>
  </select>
    <br>
    <br>
  <label for="date">Birthday: </label>
  <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
    <br>
    <br>
  <label for="description">Description: </label>
    <br>
  <textarea id="description" name="cat[description]" rows="8" cols="34"><%= @cat.description %></textarea>
    <br>
  <input type="submit" name="" value="All Done!">
</form>

Cats/app/views/cats/index.html.erb
<ol>
  <% @cats.each do |cat| %>
    <li>
      <a href="<%=cat_url(cat)%>">
        <%= cat.name %>
      </a>
    </li>
  <% end %>
</ol>

Cats/app/views/cats/new.html.erb
<h1>Tell us about your Cat</h1>
<form action=' <%=cats_url %>' method="post">
  <label for="name">Name: </label>

  <input id="name" type="text" name="cat[name]" value="">
  <br>
  <br>

  <label for="sex">Sex: </label>
    <label for="female">F</label>
    <input id="sex female" type="radio" name="cat[sex]" value="F" checked />
    <label for="male">M</label>
    <input id="sex male" type="radio" name="cat[sex]" value="M" />

  <label for="color">Color: </label>
  <select id="color" name="cat[color]">
    <option selected disabled >-- select a color --</option>
    <% CAT_COLORS.each do |c| %>
      <option ><%= c %></option>
    <% end %>
  </select>
    <br>
    <br>
  <label for="date">Birthday: </label>
  <input type="date" name="cat[birth_date]" value="">
    <br>
    <br>
  <label for="description">Description: </label>
    <br>
  <textarea id="description" name="cat[description]" rows="8" cols="34"></textarea>
    <br>
  <input type="submit" name="" value="All Done!">
</form>

Cats/app/views/cats/show.html.erb
<style>
  table,
  td {
    border: 1px solid #2e81a5;
  }

  thead,
  tfoot {
    background-color: #2e81a5;
    color: #e2850b;
  }
</style>
<table>
    <thead>
        <tr>
            <th colspan="5"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>id:<%= @cat.id %> </td>
            <td>birthdate:<%= @cat.birth_date %></td>
          	<td>color:<%= @cat.color %></td>
          	<td>name:<%= @cat.name %></td>
          	<td>sex:<%= @cat.sex%></td>
        </tr>
    </tbody>
    <tfoot>
      <tr>
          <th colspan="5"><%= @cat.description %></th>
      </tr>
    </tfoot>
</table>

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>